routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if (App::environment('production', 'staging')) {
URL::forceScheme('https');
}

Route::get('/', function () {
    return view('welcome');
});

Route::get('reset', function () {
    return view('reset');
});

Route::post('change', function () {
    return view('change');
});

Route::post('/listCity', 'CityController@ListCity');
Route::post('/addCity', 'CityController@AddCity');
Route::post('/deleteCity', 'CityController@DeleteCity');
Route::post('/updateCity', 'CityController@UpdateCity');

Route::post('/listDistrict', 'DistrictController@ListDistrict');
Route::post('/addDistrict', 'DistrictController@AddDistrict');
Route::post('/deleteDistrict', 'DistrictController@DeleteDistrict');
Route::post('/updateDistrict', 'DistrictController@UpdateDistrict');


Route::post('/listSport', 'SportController@ListSport');
Route::post('/listSportinterest', 'SportController@ListSportInterest');
Route::post('/listSportnavbar', 'SportController@ListSportNavBar');
Route::post('/addSport', 'SportController@AddSport');
Route::post('/deleteSport', 'SportController@DeleteSport');
Route::post('/updateSport', 'SportController@UpdateSport');





Route::post('/listSession', 'SessionController@ListSession');
Route::post('/addSession', 'SessionController@AddSession');
Route::post('/deleteSession', 'SessionController@DeleteSession');
Route::post('/updateSession', 'SessionController@UpdateSession');
Route::post('/getSessionDetails', 'SessionController@GetSessionDetails');

Route::post('/listLocation', 'LocationController@ListLocation');
Route::post('/addLocation', 'LocationController@AddLocation');
Route::post('/deleteLocation', 'LocationController@DeleteLocation');
Route::post('/updateLocation', 'LocationController@UpdateLocation');
Route::post('/listLocationAttachedToProvider', 'LocationController@ListLocationAtttachedToProvider');

Route::post('/listPlan', 'PlanController@ListPlan');
Route::post('/addPlan', 'PlanController@AddPlan');
Route::post('/deletePlan', 'PlanController@DeletePlan');
Route::post('/updatePlan', 'PlanController@UpdatePlan');

Route::post('/listRegPromo', 'RegisterPromoController@ListRegPromo');


Route::post('/listProvider', 'ProviderController@ListProvider');
Route::post('/listCancellationRule', 'CancellationRuleController@ListCancellationRule');
Route::post('/addCancellationRule', 'CancellationRuleController@AddCancellationRule');
Route::post('/updateCancellationRule', 'CancellationRuleController@UpdateCancellationRule');
Route::post('/deleteCancellationRule', 'CancellationRuleController@DeleteCancellationRule');


Route::post('/listRegPromo', 'RegisterPromoController@ListRegPromo');
Route::post('/addRegPromo', 'RegisterPromoController@AddRegPromo');
Route::post('/deleteRegPromo', 'RegisterPromoController@DeleteRegPromo');
Route::post('/updateRegPromo', 'RegisterPromoController@UpdateRegPromo');


Route::post('/listPromoCode', 'PromoCodeController@ListPromoCode');
Route::post('/deletePromoCode', 'PromoCodeController@DeletePromoCode');
Route::post('/updatePromoCode', 'PromoCodeController@UpdatePromoCode');
Route::post('/addPromoCode', 'PromoCodeController@AddPromoCode');


Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});


 		Route::group(['as'  => 'test.', 'prefix' => 'test'], function () {
   		    Voyager::routes();
            Route::get('/', ['uses' => 'BookController@GetBookedSessionAttachedtoProvider','as' => 'index']);
        });
        
        Route::group(['as'     => 'generateReceipt.','prefix' => 'generateReceipt' ], function ()  {
            Voyager::routes();
            Route::post('/', ['uses' => 'ReceiptController@GenerateReceipt','as' => 'index']);
        });

        Route::group([ 'as'     => 'revokedReceipt.',  'prefix' => 'revokedReceipt'], function ()  {
            Voyager::routes();
            Route::get('/', ['uses' => 'ReceiptController@RevokedReceipt','as' => 'index']);
        });
            Route::group([ 'as'     => 'paidReceipt.',  'prefix' => 'paidReceipt.'], function ()  {
                Voyager::routes();
                Route::get('/', ['uses' => 'ReceiptController@PaidReceipt','as' => 'index']);
            });

resources/views/partials/bulk-generate-receipt.blade.php
<a class="btn btn-primary pull-right" id="bulk_delete_btn"><i class="voyager-receipt"></i> <span>generate receipt</span></a>

{{-- Bulk delete modal --}}
<div class="modal modal-default fade" tabindex="-1" id="bulk_delete_modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">
                    <i class="voyager-receipt"></i> generate receipt<span id="bulk_delete_count"></span> <span id="bulk_delete_display_name"></span>?
                </h4>
            </div>
            <div class="modal-body" id="bulk_delete_modal_body">
            </div>
            <div class="modal-footer">
                <form action="{{ route('generateReceipt.index') }}"  method="POST">
                    
                    {{ csrf_field() }}
                    <input type="hidden" name="ids" id="bulk_delete_input" value="">
                    <input type="submit" class="btn btn-primary pull-right delete-confirm"
                             value="Generate">
                </form>
                <button type="button" class="btn btn-default pull-right" data-dismiss="modal">
                    {{ __('voyager.generic.cancel') }}
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
window.onload = function () {
    // Bulk delete selectors
    var $bulkDeleteBtn = $('#bulk_delete_btn');
    var $bulkDeleteModal = $('#bulk_delete_modal');
    var $bulkDeleteCount = $('#bulk_delete_count');
    var $bulkDeleteDisplayName = $('#bulk_delete_display_name');
    var $bulkDeleteInput = $('#bulk_delete_input');
    // Reposition modal to prevent z-index issues
    $bulkDeleteModal.appendTo('body');
    // Bulk delete listener
    $bulkDeleteBtn.click(function () {
        var ids = [];
        var $checkedBoxes = $('#dataTable input[type=checkbox]:checked');
        var count = $checkedBoxes.length;
        if (count) {
            // Reset input value
            $bulkDeleteInput.val('');
            // Deletion info
           
            // Gather IDs
            $.each($checkedBoxes, function () {
                var value = $(this).val();
                ids.push(value);
            })
            // Set input value
            $bulkDeleteInput.val(ids);
            // Show modal
            $bulkDeleteModal.modal('show');
        } else {
            // No row selected
            toastr.warning('no receipts selected');
        }
    });
}
</script>